# Generated by Django 3.0.7 on 2020-07-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20200702_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Blog.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='user icon.png', upload_to=''),
        ),
    ]
