# Generated by Django 3.0.7 on 2020-07-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_post_read_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleStatistics',
        ),
    ]
